# This file was created automatically with `jupyter-book init --gh-pages` 🪄 💚
# Ensure your GitHub Pages settings for this repository are set to deploy with **GitHub Actions**.

name: Submit a new notebook
on:
  issues:
    types: [labeled]

jobs:
  create-pr:
    # Only runif the notebook has the label "notebook inclusion"
    if: contains(github.event.issue.labels.*.name, 'notebook inclusion')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Parse Issue Form
        id: parse
        uses: zentered/issue-forms-body-parser@v3.0.0
        with:
          body: ${{ github.event.issue.body }}

      - name: Show parsed data JSON
        env:
          parsed_data: ${{ steps.parse.outputs.data }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          cat << EOF > pr_test_file.md
          ==========================================
          ISSUE NUMBER: #${ISSUE_NUMBER}
          ISSUE TITLE: ${ISSUE_TITLE}
          ==========================================
          ==========================================
          JSON: ${parsed_data}
          ==========================================
          EOF
          
      - name: Append Repository Details to notebook.yml
        env:
          PARSED_DATA: ${{ steps.parse.outputs.data }}
          BODY: ${{ github.event.issue.body }}
        run: |
          # 1. Add a leading newline before the block
          echo "" >> notebooks.yml
          # 2.1 Slice out Repository Details
          # 2.2. Skip empty lines or lines matching 'notebooks:'
          # 2.3. Indent remaining lines by 2 spaces
          echo "$BODY" | awk '
            /### Repository Details/ { flag=1; next }
            /### / { flag=0 }
            flag && !/notebooks:/ && NF { print "  " $0 }
          ' >> notebooks.yml
          # 3. Add a trailing newline after the block
          echo "" >> notebooks.yml

          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "test: generate dummy file for issue #${{ github.event.issue.number }}"
          committer: "GitHub Actions Bot <actions@github.com>"
          author: "GitHub Actions Bot <actions@github.com>"
          title: "Test PR from Issue #${{ github.event.issue.number }}"
          body: "This is a static test PR triggered by Issue #${{ github.event.issue.number }}."
          branch: "test-pr-issue-${{ github.event.issue.number }}"
          delete-branch: false
          
